In [ ]:
# default_exp loss

In [ ]:
from nbdev.showdoc import show_doc

# Loss

> loss functions

## MSELoss

Mean Squared Error Loss

In [ ]:
#export
from fastai.losses import *
from torch.nn import MSELoss
from fastai.basics import *
from fastai.torch_core import Module

In [ ]:
a = torch.rand(1,2,10)
b = torch.rand(1,2,10)

In [ ]:
MSELoss()(a,b)

tensor(0.2124)

In [ ]:
MSELossFlat()(a,b)

TensorBase(0.2124)

In [ ]:
#hide 
#export 
def mse(a,b):
    a = a.view(-1)
    b = b.view(-1)
    return ((a-b)**(2)).sum()/a.shape[0]

In [ ]:
show_doc(mse)

<h4 id="mse" class="doc_header"><code>mse</code><a href="__main__.py#L3" class="source_link" style="float:right">[source]</a></h4>

> <code>mse</code>(**`a`**, **`b`**)



In [ ]:
mse(a,b)

tensor(0.2124)

In [ ]:
assert mse(a,b) == MSELoss()(a,b)

In [ ]:
assert mse(a,b) == MSELossFlat()(a,b)

In [ ]:
Module

fastai.torch_core.Module

In [ ]:
#export 
class MSE_(Module):
    def forward(self,a,b):
        a = a.view(-1)
        b = b.view(-1)
        return ((a-b)**(2)).sum()/a.shape[0]

In [ ]:
show_doc(MSE_)

<h2 id="MSE_" class="doc_header"><code>class</code> <code>MSE_</code><a href="" class="source_link" style="float:right">[source]</a></h2>

> <code>MSE_</code>() :: `Module`

Same as `nn.Module`, but no need for subclasses to call `super().__init__`

In [ ]:
show_doc(MSE_.forward)

<h4 id="MSE_.forward" class="doc_header"><code>MSE_.forward</code><a href="__main__.py#L3" class="source_link" style="float:right">[source]</a></h4>

> <code>MSE_.forward</code>(**`a`**, **`b`**)

Defines the computation performed at every call.

Should be overridden by all subclasses.

.. note::
    Although the recipe for forward pass needs to be defined within
    this function, one should call the :class:`Module` instance afterwards
    instead of this since the former takes care of running the
    registered hooks while the latter silently ignores them.

In [ ]:
MSE_()(a,b)

tensor(0.2124)

In [ ]:
assert MSE_()(a,b) == MSELoss()(a,b)

## Cross Entropy

Cross Entropy loss

In [ ]:
from torch.nn import CrossEntropyLoss

In [ ]:
a = torch.randn(8, 5)
a.shape

torch.Size([8, 5])

In [ ]:
a

tensor([[ 1.0755,  0.1132,  0.1508,  0.6993, -0.3739],
        [-0.3297,  0.0908, -0.5403, -0.7752,  1.7845],
        [-0.7443,  0.2476, -1.1795,  0.6779, -0.9991],
        [ 1.5169, -0.7164,  0.5926,  0.6316,  0.3599],
        [-0.5650,  0.1970, -0.6371,  0.1027, -0.0699],
        [-0.1485,  0.9758,  0.1507, -0.8089,  0.2489],
        [-0.4890, -0.7603,  1.1785,  0.0448,  0.6035],
        [-0.1472,  2.0987,  0.0561,  0.3933, -0.1164]])

In [ ]:
b = torch.randint(0, 5, (8,))
b.shape

torch.Size([8])

In [ ]:
b

tensor([3, 1, 0, 3, 1, 3, 4, 2])

In [ ]:
CrossEntropyLossFlat()(a,b)

TensorBase(1.8933)

In [ ]:
CrossEntropyLoss()(a,b)

tensor(1.8933)

In [ ]:
def log_softmax_(a):
    o = a.exp()/a.exp().sum(1).unsqueeze(-1)
    return o.log()

In [ ]:
log_softmax_(a)

tensor([[-0.9932, -1.9555, -1.9179, -1.3694, -2.4426],
        [-2.5061, -2.0855, -2.7167, -2.9516, -0.3918],
        [-2.2262, -1.2343, -2.6615, -0.8040, -2.4810],
        [-0.8024, -3.0357, -1.7268, -1.6877, -1.9595],
        [-2.0364, -1.2745, -2.1086, -1.3687, -1.5414],
        [-2.0058, -0.8814, -1.7066, -2.6661, -1.6083],
        [-2.4637, -2.7350, -0.7962, -1.9299, -1.3712],
        [-2.6688, -0.4229, -2.4655, -2.1283, -2.6380]])

In [ ]:
torch.nn.functional.log_softmax(a)

<ipython-input-27-839ad3378bff>:1: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  torch.nn.functional.log_softmax(a)


tensor([[-0.9932, -1.9555, -1.9178, -1.3694, -2.4426],
        [-2.5061, -2.0855, -2.7167, -2.9516, -0.3918],
        [-2.2262, -1.2343, -2.6615, -0.8040, -2.4810],
        [-0.8024, -3.0357, -1.7268, -1.6877, -1.9595],
        [-2.0364, -1.2745, -2.1086, -1.3687, -1.5414],
        [-2.0058, -0.8814, -1.7066, -2.6661, -1.6083],
        [-2.4637, -2.7350, -0.7962, -1.9299, -1.3712],
        [-2.6688, -0.4229, -2.4655, -2.1283, -2.6380]])

In [ ]:
test_close(torch.nn.functional.log_softmax(a),log_softmax_(a))

<ipython-input-28-80df3adbc414>:1: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  test_close(torch.nn.functional.log_softmax(a),log_softmax_(a))


In [ ]:
b

tensor([3, 1, 0, 3, 1, 3, 4, 2])

In [ ]:
a

tensor([[ 1.0755,  0.1132,  0.1508,  0.6993, -0.3739],
        [-0.3297,  0.0908, -0.5403, -0.7752,  1.7845],
        [-0.7443,  0.2476, -1.1795,  0.6779, -0.9991],
        [ 1.5169, -0.7164,  0.5926,  0.6316,  0.3599],
        [-0.5650,  0.1970, -0.6371,  0.1027, -0.0699],
        [-0.1485,  0.9758,  0.1507, -0.8089,  0.2489],
        [-0.4890, -0.7603,  1.1785,  0.0448,  0.6035],
        [-0.1472,  2.0987,  0.0561,  0.3933, -0.1164]])

In [ ]:
-a[range(len(a)), b]

tensor([-0.6993, -0.0908,  0.7443, -0.6316, -0.1970,  0.8089, -0.6035, -0.0561])

In [ ]:
def nll_(a,b):
    o = a[range(len(a)), b]
    return -o

In [ ]:
nll_(log_softmax_(a),b)

tensor([1.3694, 2.0855, 2.2262, 1.6877, 1.2745, 2.6661, 1.3712, 2.4655])

In [ ]:
torch.nn.functional.nll_loss(torch.nn.functional.log_softmax(a),b, reduction="none")

<ipython-input-34-169ec7fd49a7>:1: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  torch.nn.functional.nll_loss(torch.nn.functional.log_softmax(a),b, reduction="none")


tensor([1.3694, 2.0855, 2.2262, 1.6877, 1.2745, 2.6661, 1.3712, 2.4655])

In [ ]:
torch.nn.functional.nll_loss(torch.nn.functional.log_softmax(a),b)

<ipython-input-35-fcdfc703bd11>:1: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  torch.nn.functional.nll_loss(torch.nn.functional.log_softmax(a),b)


tensor(1.8933)

In [ ]:
CrossEntropyLoss()(a,b)

tensor(1.8933)

In [ ]:
def ce(a,b): return nll_(log_softmax_(a),b).mean()

In [ ]:
ce(a,b)

tensor(1.8933)

In [ ]:
assert ce(a,b) == CrossEntropyLoss()(a,b)

In [ ]:
assert ce(a,b) == CrossEntropyLossFlat()(a,b)

## BCE

Binary Cross Entropy

In [ ]:
from torch.nn.functional import binary_cross_entropy, binary_cross_entropy_with_logits

In [ ]:
a = torch.randn((3, 2))
a

tensor([[ 0.0323,  1.3236],
        [ 1.7825, -1.1676],
        [-0.9347,  0.8102]])

In [ ]:
b= tensor([[1,0],[1,0],[0,1]]).float(); b

tensor([[1., 0.],
        [1., 0.],
        [0., 1.]])

In [ ]:
sa = sigmoid(a)
sa

tensor([[0.5081, 0.7898],
        [0.8560, 0.2373],
        [0.2820, 0.6922]])

In [ ]:
binary_cross_entropy(sa,b)

tensor(0.5604)

In [ ]:
binary_cross_entropy_with_logits(a,b)

tensor(0.5604)

In [ ]:
-torch.where(b==1., sa, 1-sa).log()

tensor([[0.6771, 1.5596],
        [0.1555, 0.2709],
        [0.3313, 0.3679]])

In [ ]:
binary_cross_entropy(sa,b,reduction='none')

tensor([[0.6771, 1.5596],
        [0.1555, 0.2709],
        [0.3313, 0.3679]])

In [ ]:
def bce(a,b):
    return -torch.where(b==1., sa, 1-sa).log().mean()

In [ ]:
bce(sa,b) 

tensor(0.5604)

In [ ]:
assert bce(sa,b)==binary_cross_entropy(sa,b)